### PR TITLE
Maximum subarray in cpp

### PR DESCRIPTION
**Pull request by IqraMuzaffar**
This is the optimal version of Kadane's algorithm in c++.

### CODE REVIEW

**Review by saadali18 — CHANGES_REQUESTED** [review]
Take latest pull, because one cpp file already exist for kadane_algo
Add your code in that file instead of creating new

**Comment by saadali18** [comment]
Unnecessary

**Comment by IqraMuzaffar** [comment]
Unnecessary? Didn’t get it🤔

**Comment by saadali18** [comment]
You have opened another PR, with same work https://github.com/saadali18/Leetcode-Interview-Questions/pull/8/files

**Pull request closed without merging**
